"""empty message

Revision ID: 616346e7ec1d
Revises: d936b3f1db12
Create Date: 2021-12-18 16:19:28.145679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '616346e7ec1d'
down_revision = 'd936b3f1db12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
